[2024-08-30T15:21:28.412+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:21:28.429+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:21:28.429+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-08-30T15:21:28.455+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-29 00:00:00+00:00
[2024-08-30T15:21:28.463+0000] {standard_task_runner.py:60} INFO - Started process 5120 to run task
[2024-08-30T15:21:28.477+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpllrcijs7']
[2024-08-30T15:21:28.485+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask spark_retail_analysis_task
[2024-08-30T15:21:28.529+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:21:28.599+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:21:28.834+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-08-30T15:21:28.889+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:21:28.896+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:21:35.151+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-30T15:21:35.152+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-30T15:21:35.153+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-30T15:21:35.161+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-30T15:21:35.163+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-30T15:21:35.163+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-30T15:21:35.164+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-30T15:21:35.167+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-30T15:21:35.168+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-30T15:21:35.169+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-30T15:21:35.170+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-30T15:21:35.197+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-30T15:21:35.208+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240829T000000, start_date=20240830T152128, end_date=20240830T152135
[2024-08-30T15:21:35.270+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 5120)
[2024-08-30T15:21:35.314+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:21:35.361+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-30T15:55:23.238+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:55:23.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:55:23.255+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-08-30T15:55:23.277+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-29 00:00:00+00:00
[2024-08-30T15:55:23.292+0000] {standard_task_runner.py:60} INFO - Started process 6503 to run task
[2024-08-30T15:55:23.296+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpmymsnorp']
[2024-08-30T15:55:23.298+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask spark_retail_analysis_task
[2024-08-30T15:55:23.325+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:55:23.382+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:55:23.553+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-08-30T15:55:23.574+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:55:23.577+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:55:26.436+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-30T15:55:26.437+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-30T15:55:26.438+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-30T15:55:26.439+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-30T15:55:26.440+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-30T15:55:26.440+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-30T15:55:26.441+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-30T15:55:26.442+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-30T15:55:26.443+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-30T15:55:26.444+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-30T15:55:26.444+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-30T15:55:26.465+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-30T15:55:26.471+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240829T000000, start_date=20240830T155523, end_date=20240830T155526
[2024-08-30T15:55:26.494+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 6503)
[2024-08-30T15:55:26.540+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:55:26.568+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
