[2024-08-30T15:16:05.995+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:16:06.020+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:16:06.021+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-08-30T15:16:06.057+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-29 00:00:00+00:00
[2024-08-30T15:16:06.069+0000] {standard_task_runner.py:60} INFO - Started process 4863 to run task
[2024-08-30T15:16:06.091+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmp4r04ok0r']
[2024-08-30T15:16:06.108+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask spark_retail_analysis_task
[2024-08-30T15:16:06.707+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:16:07.123+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:16:08.230+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-08-30T15:16:08.393+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:16:08.408+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:16:27.235+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-30T15:16:27.237+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-30T15:16:27.239+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-30T15:16:27.240+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-30T15:16:27.242+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-30T15:16:27.243+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-30T15:16:27.244+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-30T15:16:27.249+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-30T15:16:27.251+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-30T15:16:27.252+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-30T15:16:27.253+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-30T15:16:27.293+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-30T15:16:27.302+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240829T000000, start_date=20240830T151605, end_date=20240830T151627
[2024-08-30T15:16:27.369+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 4863)
[2024-08-30T15:16:27.390+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:16:27.423+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-30T15:50:15.875+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:50:15.890+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T15:50:15.891+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-08-30T15:50:15.915+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-29 00:00:00+00:00
[2024-08-30T15:50:15.925+0000] {standard_task_runner.py:60} INFO - Started process 6257 to run task
[2024-08-30T15:50:15.930+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpw2cprlmg']
[2024-08-30T15:50:15.932+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask spark_retail_analysis_task
[2024-08-30T15:50:15.951+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-30T15:50:16.006+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task scheduled__2024-08-29T00:00:00+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-30T15:50:16.116+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-08-30T15:50:16.136+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2024-08-30T15:50:16.139+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py
[2024-08-30T15:50:21.992+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-08-30T15:50:21.994+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-08-30T15:50:21.995+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-08-30T15:50:21.996+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-08-30T15:50:21.997+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-08-30T15:50:21.997+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-08-30T15:50:21.998+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-08-30T15:50:21.998+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-08-30T15:50:21.999+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-08-30T15:50:22.000+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-08-30T15:50:22.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-08-30T15:50:22.027+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-30T15:50:22.033+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240829T000000, start_date=20240830T155015, end_date=20240830T155022
[2024-08-30T15:50:22.059+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task spark_retail_analysis_task (Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=1g --conf spark.dynamicAllocation.enabled=false --conf spark.shuffle.service.enabled=false --conf spark.jars=/opt/bitnami/spark/jars/postgresql-42.2.18.jar --name arrow-spark --queue root.default /opt/airflow/scripts/spark-retail-analysis.py. Error code is: 1.; 6257)
[2024-08-30T15:50:22.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-30T15:50:22.157+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
